### ISSUE TITLE
Entity Component System

### ISSUE THREAD

**Issue by primenumber59** [jasonliang-dev/spry#3]
I am new to an ECS, and have read a few explanations online, but do you have a link to the resource that was the inspiration for _your_ ECS to make more concrete what I am learning in spry?

Also, in the ecs example, I see that the keys (p, k, v) are checked, but I am trying to understand what the purpose of them is and what the example is illustrating. I expect that is a basic question, but if there is a link or something to provide context to the example would be helpful.

**Comment by jasonliang-dev** [comment]
The ECS is my own little thing, so I don't have any reference materials other than the [ecs](https://github.com/jasonliang-dev/spry/blob/master/examples/ecs/main.lua) and [boxes](https://github.com/jasonliang-dev/spry/blob/master/examples/boxes/main.lua) examples. but I can show you how I think about entities:

All entities are stored in a table. Each row is a single entity, identified by an integer. Each column contains the component data for each entity.

| entity | position       | velocity     | some_other_component |
|--------|----------------|--------------|-------------------|
| 1      | x = 10, y = 20 | x = 1, y = 0 | ...               |
| 2      | x = 30, y = 40 | x = 0, y = 0 | ...               |
| 3      | x = 50, y = 60 | nil          | ...               |

```lua
for id, e in ecs:select { "position", "velocity" } do
  e.position.x = e.position.x + e.velocity.x * dt
  e.position.y = e.position.y + e.velocity.y * dt
end
```

In this example, all 3 entities have a position in space. Entity 1 moves to the right. Entity 2 doesn't move because its velocity is 0. Entity 3 doesn't have a velocity component, so it doesn't get selected in the loop and its position doesn't change.

The ECS example project uses the keyboard keys:
- `p` (for position): effectively "locks" the entity's position by removing its velocity component
- `k` (for kill): removes all entities with position and velocity data
- `v` (for velocity): adds velocity data for entities that don't have a velocity component

**Comment by primenumber59** [comment]
Thank you for taking the time to explain some more about the ECS and the example. I really appreciate it, and am having such an interesting time learning to use Spry. I am so impressed with what you have made in such a small space, and also the Spry API Reference is invaluable.
